name: Test
on: [push]
jobs:
  test-macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - run: npm test
  test-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - run: npm test
  test-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - run: npm test
